<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\Core.Shared\Core.Shared.csproj" />
    <ProjectReference Include="..\Scheduler.Infrastructure\Scheduler.Infrastructure.csproj" />
    <ProjectReference Include="..\Trader.Application\Trader.Application.csproj" />
    <ProjectReference Include="..\Trader.Domain\Trader.Domain.csproj" />
  </ItemGroup>

</Project>
