<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\Core.Shared\Core.Shared.csproj" />
    <ProjectReference Include="..\Scheduler.Application\Scheduler.Application.csproj" />
    <ProjectReference Include="..\Scheduler.Domain\Scheduler.Domain.csproj" />
  </ItemGroup>

</Project>
