// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneBook.Infrastructure.Data;

#nullable disable

namespace PhoneBook.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneBookDbContext))]
    [Migration("20260730061506_Initial_PhoneBook")]
    partial class Initial_PhoneBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("phonebook")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "phonebook");
                });

            modelBuilder.Entity("PhoneBook.Domain.Entities.PhoneBookInfoView", b =>
                {
                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationUnitsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Address");

                    b.Property<string>("PartyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Email");

                    b.Property<string>("PartyMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Mobile");

                    b.Property<string>("PartyPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Phone");

                    b.Property<string>("PostContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Email");

                    b.Property<string>("PostContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Fax");

                    b.Property<string>("PostContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Mobile");

                    b.Property<string>("PostContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Phone");

                    b.ToTable((string)null);

                    b.ToView("PhoneBook_Info_View", "phonebook");
                });
#pragma warning restore 612, 618
        }
    }
}
