services:
  trader:
    image: m2931374/trader:latest
    container_name: trader
    ports:
      - "3002:80"
    restart: always
    networks:
      - prod-network

networks:
  prod-network:
    external: true
# ۱. دریافت آخرین نسخه ایمیج‌ها از داکر هاب
# docker compose -f docker-compose.Trader.Front.Prod.yml pull

# ۲. اجرای کانتینرها
# docker compose -f docker-compose.Trader.Front.Prod.yml up -d
