# -------------------- مرحله اول: build --------------------
FROM node:22-alpine AS builder

RUN corepack enable && corepack prepare pnpm@8.9.0 --activate

WORKDIR /app

# کپی فایل‌های manifest برای استفاده از کش داکر در pnpm install
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./

# کپی کل سورس پروژه (برای دسترسی به ساختار Monorepo)
COPY . .

# نصب وابستگی‌ها
RUN pnpm install --frozen-lockfile

# ساخت اپلیکیشن admin
RUN pnpm build:aksteel.admin

# -------------------- مرحله دوم: اجرا (nginx) --------------------
FROM nginx:alpine

# کپی فایل کانفیگ اختصاصی Nginx برای مدیریت React Router (404 Error)
COPY AkSteel-nginx.conf /etc/nginx/conf.d/default.conf

# کپی فایل‌های ساخته شده به Nginx
COPY --from=builder /app/dist/AKSteelAdmin /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]