services:
  aksteel-admin:
    image: m2931374/aksteel-admin:latest
    build:
      context: .
      dockerfile: Dockerfile.aksteel-admin
    ports:
      - "3000:80"
    container_name: aksteel-admin
    restart: always
    networks:
      - aksteel-network

  aksteel-website-phonebook:
    image: m2931374/aksteel-website-phonebook:latest
    build:
      context: .
      dockerfile: Dockerfile.aksteel-website-phonebook
    ports:
      - "3001:80"
    container_name: aksteel-website-phonebook
    restart: always
    networks:
      - aksteel-network

networks:
  aksteel-network:
    external: true

    # for create
    # docker login
    # docker compose build aksteel-admin aksteel-website-phonebook
    # docker compose push aksteel-admin aksteel-website-phonebook

    # cd D:\Project\NexusPlatform\FrontEnd
    # docker compose -f AkSteel-docker-compose.yml  up --build --no-cache
