services:
  aksteel-sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: aksteel_sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Fajr@123
    ports:
      - "1434:1433"
    volumes:
      - ./sqlserverdata:/var/opt/mssql2025/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Fajr@123 -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  aksteel-redis:
    image: redis:alpine
    container_name: aksteel_redis
    ports:
      - "6379:6379"

  aksteel-webapi:
    image: aksteel-webapi:latest
    container_name: aksteel_webapi
    build:
      context: .
      dockerfile: AkSteel.WebApi/Dockerfile
    # پورت مستقیم برداشته شد تا فقط از طریق Reverse Proxy دسترسی وجود داشته باشد
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=aksteel-sqlserver;Database=AksteelDb;User Id=sa;Password=Fajr@123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__Redis=aksteel-redis:6379,abortConnect=false
    depends_on:
      aksteel-sqlserver:
        condition: service_healthy
      aksteel-redis:
        condition: service_started

  aksteel-proxy:
    image: aksteel-proxy:latest
    container_name: aksteel_proxy
    build:
      context: .
      dockerfile: AkSteel.ReverseProxy/Dockerfile # مسیر دقیق Dockerfile پروکسی
    ports:
      - "80:8080" # پورت 80 سیستم اصلی به 8080 کانتینر پروکسی متصل می‌شود
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - aksteel-webapi
  
      # cd D:\Project\NexusPlatform
      # docker compose -f docker-compose.aksteel.yml up --build
      # docker compose -f docker-compose.aksteel.yml build --no-cache
      #on develope server # docker save -o aksteel-webapi.tar aksteel-webapi:latest
                            
      #on product Server # docker load -i aksteel-webapi.tar


      # docker compose -f docker-compose.aksteel.yml down
      # rename sqlserver-data sqlserver-data-old