<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\StreamBus.Application\StreamBus.Application.csproj" />
    <ProjectReference Include="..\StreamBus.Domain\StreamBus.Domain.csproj" />
  </ItemGroup>

</Project>
