<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SqlScript\CreateAssignmentTrigger.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SqlScript\CreateAssignmentTrigger.sql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
    <ProjectReference Include="..\HR.Application\HR.Application.csproj" />
    <ProjectReference Include="..\HR.Domain\HR.Domain.csproj" />
  </ItemGroup>

</Project>
