// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraderServer.Infrastructure.DependencyInjection;

#nullable disable

namespace Trader.Server.Collector.Infrastructure.Migrations
{
    [DbContext(typeof(TraderDbContext))]
    partial class TraderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trader")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.BrokerageAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("EquivalentResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Platform")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_BrokerageAccount_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_BrokerageAccount_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_BrokerageAccount_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_BrokerageAccount_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_BrokerageAccount_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_BrokerageAccount_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_BrokerageAccount_ScopedLookup");

                    b.HasIndex("Platform", "FkUserId")
                        .HasDatabaseName("IX_Option_FastLookup");

                    b.ToTable("BrokerageAccount", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("DuePrice")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("EquivalentResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkOptionContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Side")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Option_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Option_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Option_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Option_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_Option_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_Option_OwnerPerson");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Option_Title_FastLookup");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_Option_ScopedLookup");

                    b.HasIndex("Side", "FkOptionContractId", "DuePrice")
                        .HasDatabaseName("IX_Option_FastLookup");

                    b.ToTable("Options", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.OptionContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EquivalentResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkStockId")
                        .IsUnicode(false)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumberOfOpenPositionAllow")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OptionContract_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_OptionContract_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_OptionContract_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_OptionContract_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_OptionContract_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_OptionContract_OwnerPerson");

                    b.HasIndex("FkStockId", "DueDate")
                        .HasDatabaseName("IX_OptionContract_FastLookup");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_OptionContract_ScopedLookup");

                    b.ToTable("OptionContracts", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.SnapShotFromOptionTrading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("BuyOrder1Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder1Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder1Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder2Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder2Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder2Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder3Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder3Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder3Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder4Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder4Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder4Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder5Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder5Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder5Volume")
                        .HasColumnType("bigint");

                    b.Property<int?>("ClosePrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LastPrice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("NumberOfOpenPositions")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SellOrder1Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder1Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder1Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder2Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder2Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder2Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder3Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder3Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder3Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder4Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder4Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder4Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder5Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder5Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder5Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyLegalPersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyLegalPersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyOrderVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyOrdersCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyTruePersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyTruePersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellLegalPersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellLegalPersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellOrderVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellOrdersCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellTruePersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellTruePersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradedValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradedVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradesCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_OwnerPerson");

                    b.HasIndex("DateTime", "FkOptionId")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_FastLookup");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_SnapShotFromOptionTrading_ScopedLookup");

                    b.ToTable("SnapShotFromOptionTrading", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.SnapShotFromStockTrading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("BuyOrder1Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder1Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder1Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder2Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder2Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder2Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder3Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder3Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder3Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder4Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder4Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder4Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyOrder5Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("BuyOrder5Price")
                        .HasColumnType("int");

                    b.Property<long?>("BuyOrder5Volume")
                        .HasColumnType("bigint");

                    b.Property<int?>("ClosePrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkStockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LastPrice")
                        .HasColumnType("int");

                    b.Property<long?>("MarketCapitalization")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("SellOrder1Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder1Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder1Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder2Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder2Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder2Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder3Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder3Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder3Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder4Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder4Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder4Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellOrder5Count")
                        .HasColumnType("bigint");

                    b.Property<int?>("SellOrder5Price")
                        .HasColumnType("int");

                    b.Property<long?>("SellOrder5Volume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyLegalPersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyLegalPersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyOrderVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyOrdersCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyTruePersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalBuyTruePersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellLegalPersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellLegalPersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellOrderVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellOrdersCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellTruePersonalityCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalSellTruePersonalityVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradedValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradedVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTradesCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_OwnerPerson");

                    b.HasIndex("DateTime", "FkStockId")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_FastLookup");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_SnapShotFromStockTrading_ScopedLookup");

                    b.ToTable("SnapShotFromStockTrading", "trader");
                });

            modelBuilder.Entity("Trader.Server.Collector.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BuyCommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("CodeOfTsetmc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("EquivalentResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MinValueBuyOrder")
                        .HasColumnType("int");

                    b.Property<int?>("MinValueSellOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PercentOfDailyTolerance")
                        .HasColumnType("float");

                    b.Property<TimeOnly?>("PreOpeningTimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("PreOpeningTimeStart")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("SellCommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StepPrice")
                        .HasColumnType("int");

                    b.Property<int?>("TPlus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte?>("TypeOfMarket")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Stock_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Stock_CreatedBy");

                    b.HasIndex("Isin")
                        .HasDatabaseName("IX_Stock_Isin_FastLookup");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Stock_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Stock_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_Stock_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_Stock_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_Stock_ScopedLookup");

                    b.HasIndex("Isin", "Title", "OpenTime", "TypeOfMarket")
                        .HasDatabaseName("IX_Stock_FastLookup");

                    b.ToTable("Stock", "trader");
                });
#pragma warning restore 612, 618
        }
    }
}
