// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using People.Infrastructure.Data;

#nullable disable

namespace People.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20260630105716_Edit_1_People")]
    partial class Edit_1_People
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.LegalPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RegisterCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_LegalPerson");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LegalPerson_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_LegalPerson_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_LegalPerson_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_LegalPerson_ModifiedBy");

                    b.HasIndex(new[] { "Title" }, "IX_Persons_FullName_FastLookup");

                    b.HasIndex(new[] { "RegisterCode" }, "IX_Persons_Unique")
                        .IsUnique()
                        .HasFilter("([RegisterCode] IS NOT NULL)");

                    b.HasIndex(new[] { "FkPartyId" }, "IX_legalPersons_fkPartyId");

                    b.ToTable("legalPersons", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.NaturalPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_NaturalPerson");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_NaturalPerson_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_NaturalPerson_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_NaturalPerson_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_NaturalPerson_ModifiedBy");

                    b.HasIndex(new[] { "FkPartyId" }, "IX_naturalPersons_fkPartyId");

                    b.ToTable("naturalPersons", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.NaturalPersonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool?>("Enablity")
                        .HasColumnType("bit");

                    b.Property<Guid>("FkNaturalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Remove")
                        .HasColumnType("bit");

                    b.Property<bool?>("Visiblity")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_NaturalPersonProfile");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_NaturalPersonProfile_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_NaturalPersonProfile_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_NaturalPersonProfile_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_NaturalPersonProfile_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_NaturalPersonProfile_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_NaturalPersonProfile_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_NaturalPersonProfile_ScopedLookup");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId" }, "IX_PersonProfile_OwnerOrgUnit");

                    b.HasIndex(new[] { "OwnerPersonId" }, "IX_PersonProfile_OwnerPerson");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId", "OwnerPersonId" }, "IX_PersonProfile_ScopedLookup");

                    b.HasIndex(new[] { "FkNaturalPersonId" }, "IX_PersonProfiles_FkPersonId");

                    b.ToTable("NaturalPersonProfiles", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PartiesRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FkDestinationPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkSourcePartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("RelationType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_PartiesRelation");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PartiesRelation_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PartiesRelation_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PartiesRelation_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PartiesRelation_ModifiedBy");

                    b.HasIndex(new[] { "FkDestinationPartyId" }, "IX_PartiesRelations_destinationPartyId");

                    b.HasIndex(new[] { "FkSourcePartyId" }, "IX_PartiesRelations_sourcePartyId");

                    b.ToTable("PartiesRelations", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FkPermissionAssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_Party");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Party_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Party_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Party_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Party_ModifiedBy");

                    b.ToTable("Parties", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PartyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PartyContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PartyContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PartyContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PartyContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PartyContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PartyContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_ScopedLookup");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId" }, "IX_PersonContact_OwnerOrgUnit");

                    b.HasIndex(new[] { "OwnerPersonId" }, "IX_PersonContact_OwnerPerson");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId", "OwnerPersonId" }, "IX_PersonContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPartyId" }, "IX_PersonContacts_FkPartyId");

                    b.ToTable("PartyContacts", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.LegalPerson", b =>
                {
                    b.HasOne("People.Domain.Entities.Party", "Party")
                        .WithMany("LegalPeople")
                        .HasForeignKey("FkPartyId")
                        .IsRequired()
                        .HasConstraintName("FK_legalPersons_Parties");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("People.Domain.Entities.NaturalPerson", b =>
                {
                    b.HasOne("People.Domain.Entities.Party", "Party")
                        .WithMany("NaturalPeople")
                        .HasForeignKey("FkPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_naturalPersons_Parties");

                    b.OwnsOne("Core.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("NaturalPersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("NaturalPersonId");

                            b1.HasIndex("FirstName", "LastName")
                                .HasDatabaseName("IX_Persons_FullName_FastLookup");

                            b1.ToTable("naturalPersons", "people");

                            b1.WithOwner()
                                .HasForeignKey("NaturalPersonId");
                        });

                    b.OwnsOne("Core.Domain.ValueObjects.NationalCode", "NationalCode", b1 =>
                        {
                            b1.Property<Guid>("NaturalPersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("NationalCode");

                            b1.HasKey("NaturalPersonId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Persons_Unique_NationalCode");

                            b1.ToTable("naturalPersons", "people");

                            b1.WithOwner()
                                .HasForeignKey("NaturalPersonId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("NationalCode")
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("People.Domain.Entities.NaturalPersonProfile", b =>
                {
                    b.HasOne("People.Domain.Entities.NaturalPerson", "NaturalPerson")
                        .WithMany("NaturalPersonProfiles")
                        .HasForeignKey("FkNaturalPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NaturalPersonProfiles_naturalPersons");

                    b.Navigation("NaturalPerson");
                });

            modelBuilder.Entity("People.Domain.Entities.PartiesRelation", b =>
                {
                    b.HasOne("People.Domain.Entities.Party", "DestinationParty")
                        .WithMany("PartiesRelationFkDestinationParties")
                        .HasForeignKey("FkDestinationPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PartiesRelations_Parties1");

                    b.HasOne("People.Domain.Entities.Party", "SourceParty")
                        .WithMany("PartiesRelationFkSourceParties")
                        .HasForeignKey("FkSourcePartyId")
                        .IsRequired()
                        .HasConstraintName("FK_PartiesRelations_Parties");

                    b.Navigation("DestinationParty");

                    b.Navigation("SourceParty");
                });

            modelBuilder.Entity("People.Domain.Entities.PartyContact", b =>
                {
                    b.HasOne("People.Domain.Entities.Party", "Party")
                        .WithMany("PartyContacts")
                        .HasForeignKey("FkPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PartyContacts_Parties");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("People.Domain.Entities.NaturalPerson", b =>
                {
                    b.Navigation("NaturalPersonProfiles");
                });

            modelBuilder.Entity("People.Domain.Entities.Party", b =>
                {
                    b.Navigation("LegalPeople");

                    b.Navigation("NaturalPeople");

                    b.Navigation("PartiesRelationFkDestinationParties");

                    b.Navigation("PartiesRelationFkSourceParties");

                    b.Navigation("PartyContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
