// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using People.Infrastructure.Data;

#nullable disable

namespace People.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.Parties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Parties_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Parties_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Parties_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Parties_ModifiedBy");

                    b.ToTable("Parties", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PartiesRelations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("destinationPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("relationType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("sourcePartyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PartiesRelations_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PartiesRelations_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PartiesRelations_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PartiesRelations_ModifiedBy");

                    b.HasIndex("destinationPartyId");

                    b.HasIndex("sourcePartyId");

                    b.ToTable("PartiesRelations", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PersonContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PersonContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PersonContact_CreatedBy");

                    b.HasIndex("FkPartyId");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PersonContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PersonContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PersonContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PersonContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PersonContact_ScopedLookup");

                    b.ToTable("PersonContacts", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PersonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool?>("Enablity")
                        .HasColumnType("bit");

                    b.Property<Guid>("FkPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Remove")
                        .HasColumnType("bit");

                    b.Property<bool?>("Visiblity")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PersonProfile_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PersonProfile_CreatedBy");

                    b.HasIndex("FkPersonId");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PersonProfile_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PersonProfile_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PersonProfile_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PersonProfile_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PersonProfile_ScopedLookup");

                    b.ToTable("PersonProfiles", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.legalPersons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RegisterCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("fkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_legalPersons_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_legalPersons_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_legalPersons_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_legalPersons_ModifiedBy");

                    b.HasIndex("RegisterCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Persons_Unique")
                        .HasFilter("[RegisterCode] IS NOT NULL");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Persons_FullName_FastLookup");

                    b.HasIndex("fkPartyId");

                    b.ToTable("legalPersons", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.naturalPersons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("fkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_naturalPersons_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_naturalPersons_CreatedBy");

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_naturalPersons_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_naturalPersons_ModifiedBy");

                    b.HasIndex("fkPartyId");

                    b.ToTable("naturalPersons", "people");
                });

            modelBuilder.Entity("People.Domain.Entities.PartiesRelations", b =>
                {
                    b.HasOne("People.Domain.Entities.Parties", "destinationParty")
                        .WithMany("destinationRealations")
                        .HasForeignKey("destinationPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("People.Domain.Entities.Parties", "sourceParty")
                        .WithMany("sourceRealations")
                        .HasForeignKey("sourcePartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("destinationParty");

                    b.Navigation("sourceParty");
                });

            modelBuilder.Entity("People.Domain.Entities.PersonContact", b =>
                {
                    b.HasOne("People.Domain.Entities.Parties", "party")
                        .WithMany("contacts")
                        .HasForeignKey("FkPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("party");
                });

            modelBuilder.Entity("People.Domain.Entities.PersonProfile", b =>
                {
                    b.HasOne("People.Domain.Entities.naturalPersons", "person")
                        .WithMany("Profiles")
                        .HasForeignKey("FkPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("People.Domain.Entities.legalPersons", b =>
                {
                    b.HasOne("People.Domain.Entities.Parties", "party")
                        .WithMany("legalPersons")
                        .HasForeignKey("fkPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("party");
                });

            modelBuilder.Entity("People.Domain.Entities.naturalPersons", b =>
                {
                    b.HasOne("People.Domain.Entities.Parties", "Party")
                        .WithMany("NaturalPersons")
                        .HasForeignKey("fkPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("naturalPersonsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("naturalPersonsId");

                            b1.HasIndex("FirstName", "LastName")
                                .HasDatabaseName("IX_Persons_FullName_FastLookup");

                            b1.ToTable("naturalPersons", "people");

                            b1.WithOwner()
                                .HasForeignKey("naturalPersonsId");
                        });

                    b.OwnsOne("Core.Domain.ValueObjects.NationalCode", "NationalCode", b1 =>
                        {
                            b1.Property<Guid>("naturalPersonsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("NationalCode");

                            b1.HasKey("naturalPersonsId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Persons_Unique_NationalCode");

                            b1.ToTable("naturalPersons", "people");

                            b1.WithOwner()
                                .HasForeignKey("naturalPersonsId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("NationalCode")
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("People.Domain.Entities.Parties", b =>
                {
                    b.Navigation("NaturalPersons");

                    b.Navigation("contacts");

                    b.Navigation("destinationRealations");

                    b.Navigation("legalPersons");

                    b.Navigation("sourceRealations");
                });

            modelBuilder.Entity("People.Domain.Entities.naturalPersons", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
