// <auto-generated />
using System;
using HR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20260802044130_Edit_5_HR")]
    partial class Edit_5_HR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_Assignment");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Assignment_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Assignment_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Assignment_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Assignment_ModifiedBy");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_Assignments_EmploymentId");

                    b.HasIndex(new[] { "FkPostId" }, "IX_Assignments_PostId");

                    b.ToTable("Assignments", "hr", t =>
                        {
                            t.HasTrigger("trg_Assignments_CheckOverlap");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CostCenter");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" CostCenter", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmployementInfoView", b =>
                {
                    b.Property<int>("AssignmentsAssigneeType")
                        .HasColumnType("int")
                        .HasColumnName("Assignments_AssigneeType");

                    b.Property<DateOnly>("AssignmentsEffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("Assignments_EffectiveFrom");

                    b.Property<DateOnly?>("AssignmentsEffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("Assignments_EffectiveTo");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CostCenter_Name");

                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Email");

                    b.Property<string>("EmploymentContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Fax");

                    b.Property<string>("EmploymentContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Mobile");

                    b.Property<string>("EmploymentContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Phone");

                    b.Property<DateOnly>("EmploymentEffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("Employment_EffectiveFrom");

                    b.Property<DateOnly?>("EmploymentEffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("Employment_EffectiveTo");

                    b.Property<DateOnly?>("EmploymentLocationsEffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("EmploymentLocations_EffectiveFrom");

                    b.Property<DateOnly?>("EmploymentLocationsEffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("EmploymentLocations_EffectiveTo");

                    b.Property<string>("EmploymentStatusName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employment_Status_Name");

                    b.Property<string>("EmploymentTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Employment_Type_Name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GradeTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Grade_Title");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobLevel_Title");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle_Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Location_Title");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OrganizationUnitsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("OrganizationUnits_Name");

                    b.Property<string>("PartyAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Address");

                    b.Property<string>("PartyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Email");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Party_Id");

                    b.Property<string>("PartyMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Mobile");

                    b.Property<string>("PartyPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Phone");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post_Code");

                    b.Property<string>("PostContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Email");

                    b.Property<string>("PostContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Fax");

                    b.Property<string>("PostContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Mobile");

                    b.Property<string>("PostContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Phone");

                    b.ToTable((string)null);

                    b.ToView("Employement_Info_View", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkEmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkEmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkNaturalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_Employment");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Employment_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Employment_CreatedBy");

                    b.HasIndex("FkEmploymentStatusId");

                    b.HasIndex("FkEmploymentTypeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Employment_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Employment_ModifiedBy");

                    b.ToTable(" Employment", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmploymentContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_EmploymentContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_ScopedLookup");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_PersonContacts_FkEmploymentId");

                    b.ToTable("EmploymentContacts", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentLocation");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmploymentLocation_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_EmploymentLocation_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_EmploymentLocation_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_EmploymentLocation_ModifiedBy");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_ EmploymentLocations_fkEmploymentId");

                    b.HasIndex(new[] { "FkLocationId" }, "IX_ EmploymentLocations_fkLocationId");

                    b.ToTable(" EmploymentLocations", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentStatus");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" EmploymentStatus", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentType");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" EmploymentType", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Grade");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" Grade", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_JobLevel");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("JobLevel", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_JobTitle");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_JobTitle_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_JobTitle_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_JobTitle_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_JobTitle_ModifiedBy");

                    b.ToTable("JobTitle", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Location");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Location_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Location_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Location_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Location_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.ToTable("Location", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_OrganizationUnit");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OrganizationUnit_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_OrganizationUnit_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_OrganizationUnit_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_OrganizationUnit_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Code" }, "IX_OrganizationUnits_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "Path" }, "IX_OrganizationUnits_Path");

                    b.ToTable("OrganizationUnits", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkCostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkJobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPermissionAssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Post");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Post_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Post_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Post_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Post_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "FkCostCenterId" }, "IX_Post_CostCenterId");

                    b.HasIndex(new[] { "FkGradeId" }, "IX_Post_GradeId");

                    b.HasIndex(new[] { "FkJobLevelId" }, "IX_Post_JobLevelId");

                    b.HasIndex(new[] { "FkJobTitleId" }, "IX_Post_JobTitleId");

                    b.HasIndex(new[] { "FkOrganizationUnitId" }, "IX_Post_OrganizationUnitId");

                    b.ToTable("Post", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.PostContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PostContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PostContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PostContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PostContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PostContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PostContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPostId" }, "IX_PersonContacts_FkPostId");

                    b.ToTable("PostContacts", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.PostInfoView", b =>
                {
                    b.Property<int?>("AssignmentsAssigneeType")
                        .HasColumnType("int")
                        .HasColumnName("Assignments_AssigneeType");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CostCenter_Name");

                    b.Property<string>("EmploymentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FkCostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkJobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("GradeTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Grade_Title");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobLevel_Title");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationUnitsName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("OrganizationUnits_Name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post_Code");

                    b.ToTable((string)null);

                    b.ToView("Post_Info_View", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("Assignments")
                        .HasForeignKey("FkEmploymentId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_ Employment");

                    b.HasOne("HR.Domain.Entities.Post", "Post")
                        .WithMany("Assignments")
                        .HasForeignKey("FkPostId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Post");

                    b.Navigation("Employment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.HasOne("HR.Domain.Entities.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employments")
                        .HasForeignKey("FkEmploymentStatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ Employment_ EmploymentStatus");

                    b.HasOne("HR.Domain.Entities.EmploymentType", "EmploymentType")
                        .WithMany("Employments")
                        .HasForeignKey("FkEmploymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ Employment_ EmploymentType");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentContact", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("EmploymentContacts")
                        .HasForeignKey("FkEmploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmploymentContacts_Employments");

                    b.Navigation("Employment");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("FkEmploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ EmploymentLocations_ Employment");

                    b.HasOne("HR.Domain.Entities.Location", "Location")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("FkLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ EmploymentLocations_Location");

                    b.Navigation("Employment");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.HasOne("HR.Domain.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.HasOne("HR.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("Posts")
                        .HasForeignKey("FkCostCenterId")
                        .HasConstraintName("FK_Post_ CostCenter");

                    b.HasOne("HR.Domain.Entities.Grade", "Grade")
                        .WithMany("Posts")
                        .HasForeignKey("FkGradeId")
                        .HasConstraintName("FK_Post_ Grade");

                    b.HasOne("HR.Domain.Entities.JobLevel", "JobLevel")
                        .WithMany("Posts")
                        .HasForeignKey("FkJobLevelId")
                        .HasConstraintName("FK_Post_JobLevel");

                    b.HasOne("HR.Domain.Entities.JobTitle", "JobTitle")
                        .WithMany("Posts")
                        .HasForeignKey("FkJobTitleId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_JobTitle");

                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "OrganizationUnit")
                        .WithMany("Posts")
                        .HasForeignKey("FkOrganizationUnitId")
                        .HasConstraintName("FK_Post_OrganizationUnits");

                    b.HasOne("HR.Domain.Entities.Post", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CostCenter");

                    b.Navigation("Grade");

                    b.Navigation("JobLevel");

                    b.Navigation("JobTitle");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.PostContact", b =>
                {
                    b.HasOne("HR.Domain.Entities.Post", "Post")
                        .WithMany("PostContacts")
                        .HasForeignKey("FkPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostContacts_Posts");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("EmploymentContacts");

                    b.Navigation("EmploymentLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmploymentLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");

                    b.Navigation("PostContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
