// <auto-generated />
using System;
using HR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Migrations
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20260630112525_Edit2_HR")]
    partial class Edit2_HR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_Assignment");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Assignment_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Assignment_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Assignment_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Assignment_ModifiedBy");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_Assignments_EmploymentId");

                    b.HasIndex(new[] { "FkPostId" }, "IX_Assignments_PostId");

                    b.ToTable("Assignments", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CostCenter");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" CostCenter", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkEmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkEmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkNaturalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Employment");

                    b.HasIndex("FkEmploymentStatusId");

                    b.HasIndex("FkEmploymentTypeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" Employment", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FkEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentLocation");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmploymentLocation_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_EmploymentLocation_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_EmploymentLocation_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_EmploymentLocation_ModifiedBy");

                    b.HasIndex(new[] { "FkEmployeeId" }, "IX_ EmploymentLocations_fkEmployeeId");

                    b.HasIndex(new[] { "FkLocationId" }, "IX_ EmploymentLocations_fkLocationId");

                    b.ToTable(" EmploymentLocations", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentStatus");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" EmploymentStatus", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentType");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" EmploymentType", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Grade");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable(" Grade", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_JobLevel");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("JobLevel", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_JobTitle");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("JobTitle", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Location");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Location_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Location_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Location_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Location_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.ToTable("Location", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_OrganizationUnit");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OrganizationUnit_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_OrganizationUnit_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_OrganizationUnit_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_OrganizationUnit_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Code" }, "IX_OrganizationUnits_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "Path" }, "IX_OrganizationUnits_Path");

                    b.ToTable("OrganizationUnits", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("FkCostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkJobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPermissionAssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_Post");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Post_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Post_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_Post_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_Post_ModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "FkCostCenterId" }, "IX_Post_CostCenterId");

                    b.HasIndex(new[] { "FkGradeId" }, "IX_Post_GradeId");

                    b.HasIndex(new[] { "FkJobLevelId" }, "IX_Post_JobLevelId");

                    b.HasIndex(new[] { "FkJobTitleId" }, "IX_Post_JobTitleId");

                    b.HasIndex(new[] { "FkOrganizationUnitId" }, "IX_Post_OrganizationUnitId");

                    b.ToTable("Post", "hr");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("Assignments")
                        .HasForeignKey("FkEmploymentId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_ Employment");

                    b.HasOne("HR.Domain.Entities.Post", "Post")
                        .WithMany("Assignments")
                        .HasForeignKey("FkPostId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Post");

                    b.Navigation("Employment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.HasOne("HR.Domain.Entities.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employments")
                        .HasForeignKey("FkEmploymentStatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ Employment_ EmploymentStatus1");

                    b.HasOne("HR.Domain.Entities.EmploymentType", "EmploymentType")
                        .WithMany("Employments")
                        .HasForeignKey("FkEmploymentTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ Employment_ EmploymentType1");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employee")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("FkEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ EmploymentLocations_ Employment");

                    b.HasOne("HR.Domain.Entities.Location", "Location")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("FkLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ EmploymentLocations_Location");

                    b.Navigation("Employee");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.HasOne("HR.Domain.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.HasOne("HR.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("Posts")
                        .HasForeignKey("FkCostCenterId")
                        .HasConstraintName("FK_Post_ CostCenter");

                    b.HasOne("HR.Domain.Entities.Grade", "Grade")
                        .WithMany("Posts")
                        .HasForeignKey("FkGradeId")
                        .HasConstraintName("FK_Post_ Grade");

                    b.HasOne("HR.Domain.Entities.JobLevel", "JobLevel")
                        .WithMany("Posts")
                        .HasForeignKey("FkJobLevelId")
                        .HasConstraintName("FK_Post_JobLevel");

                    b.HasOne("HR.Domain.Entities.JobTitle", "JobTitle")
                        .WithMany("Posts")
                        .HasForeignKey("FkJobTitleId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_JobTitle");

                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "OrganizationUnit")
                        .WithMany("Posts")
                        .HasForeignKey("FkOrganizationUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_OrganizationUnits");

                    b.HasOne("HR.Domain.Entities.Post", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CostCenter");

                    b.Navigation("Grade");

                    b.Navigation("JobLevel");

                    b.Navigation("JobTitle");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("EmploymentLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmploymentLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
