// <auto-generated />
using System;
using Contact.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact.Infrastructure.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20260819175304_Edit_4_Contact")]
    partial class Edit_4_Contact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contact")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact.Domain.Entities.ContactItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContactProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentContactItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RelationType")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ContactItem");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ContactItem_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_ContactItem_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_ContactItem_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_ContactItem_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_ContactItem_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_ContactItem_OwnerPerson");

                    b.HasIndex("ParentContactItemId");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_ContactItem_ScopedLookup");

                    b.HasIndex(new[] { "ContactProfileId" }, "IX_ContactItems_ContactProfileId");

                    b.ToTable("ContactItems", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.ContactProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ProfileType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_ContactProfile");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ContactProfile_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_ContactProfile_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_ContactProfile_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_ContactProfile_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_ContactProfile_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_ContactProfile_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_ContactProfile_ScopedLookup");

                    b.ToTable("ContactProfiles", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PhoneBookInfoView", b =>
                {
                    b.Property<string>("EmpLocationContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmpLocationContact_Email");

                    b.Property<string>("EmpLocationContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmpLocationContact_Fax");

                    b.Property<string>("EmpLocationContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmpLocationContact_Mobile");

                    b.Property<string>("EmpLocationContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmpLocationContact_Phone");

                    b.Property<string>("EmploymentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Email");

                    b.Property<string>("EmploymentContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Fax");

                    b.Property<string>("EmploymentContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Mobile");

                    b.Property<string>("EmploymentContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Phone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OrganizationUnitsName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Address");

                    b.Property<string>("PartyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Email");

                    b.Property<string>("PartyMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Mobile");

                    b.Property<string>("PartyPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Phone");

                    b.Property<string>("PostContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Email");

                    b.Property<string>("PostContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Fax");

                    b.Property<string>("PostContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Mobile");

                    b.Property<string>("PostContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Phone");

                    b.Property<string>("PostLocationContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostLocationContact_Email");

                    b.Property<string>("PostLocationContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostLocationContact_Fax");

                    b.Property<string>("PostLocationContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostLocationContact_Mobile");

                    b.Property<string>("PostLocationContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostLocationContact_Phone");

                    b.Property<string>("PostLocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("PhoneBook_Info_View", "contact");
                });

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.ContactItem", b =>
                {
                    b.HasOne("Contact.Domain.Entities.ContactProfile", "ContactProfile")
                        .WithMany("ContactItems")
                        .HasForeignKey("ContactProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContactItems_ContactProfiles");

                    b.HasOne("Contact.Domain.Entities.ContactItem", "ParentContactItem")
                        .WithMany("ChildContactItems")
                        .HasForeignKey("ParentContactItemId");

                    b.Navigation("ContactProfile");

                    b.Navigation("ParentContactItem");
                });

            modelBuilder.Entity("Contact.Domain.Entities.ContactItem", b =>
                {
                    b.Navigation("ChildContactItems");
                });

            modelBuilder.Entity("Contact.Domain.Entities.ContactProfile", b =>
                {
                    b.Navigation("ContactItems");
                });
#pragma warning restore 612, 618
        }
    }
}
