// <auto-generated />
using System;
using Contact.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact.Infrastructure.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20260814165945_Edit_2_Contact")]
    partial class Edit_2_Contact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contact")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact.Domain.Entities.EmploymentContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmploymentContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_EmploymentContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_ScopedLookup");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_PersonContacts_FkEmploymentId");

                    b.ToTable("EmploymentContacts", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.LocationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_LocationContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LocationContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_LocationContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_LocationContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_LocationContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_LocationContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_LocationContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_LocationContact_ScopedLookup");

                    b.HasIndex(new[] { "FkLocationId" }, "IX_LocationContacts_FkLocationId");

                    b.ToTable("LocationContacts", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PartyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PartyContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PartyContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PartyContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PartyContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PartyContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PartyContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_ScopedLookup");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId" }, "IX_PersonContact_OwnerOrgUnit");

                    b.HasIndex(new[] { "OwnerPersonId" }, "IX_PersonContact_OwnerPerson");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId", "OwnerPersonId" }, "IX_PersonContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPartyId" }, "IX_PersonContacts_FkPartyId");

                    b.ToTable("PartyContacts", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PhoneBookInfoView", b =>
                {
                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Email");

                    b.Property<string>("EmploymentContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Fax");

                    b.Property<string>("EmploymentContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Mobile");

                    b.Property<string>("EmploymentContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Phone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationUnitsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Address");

                    b.Property<string>("PartyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Email");

                    b.Property<string>("PartyMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Mobile");

                    b.Property<string>("PartyPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Phone");

                    b.Property<string>("PostContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Email");

                    b.Property<string>("PostContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Fax");

                    b.Property<string>("PostContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Mobile");

                    b.Property<string>("PostContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Phone");

                    b.ToTable((string)null);

                    b.ToView("PhoneBook_Info_View", "contact");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PostContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PostContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PostContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PostContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PostContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PostContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PostContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPostId" }, "IX_PersonContacts_FkPostId");

                    b.ToTable("PostContacts", "contact");
                });

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "contact");
                });
#pragma warning restore 612, 618
        }
    }
}
