// <auto-generated />
using System;
using Contact.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact.Infrastructure.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    partial class ContactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contact")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact.Domain.Entities.EmploymentContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_EmploymentContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_EmploymentContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_EmploymentContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_EmploymentContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_EmploymentContact_ScopedLookup");

                    b.HasIndex(new[] { "FkEmploymentId" }, "IX_PersonContacts_FkEmploymentId");

                    b.ToTable("EmploymentContacts", "hr");
                });

            modelBuilder.Entity("Contact.Domain.Entities.LocationContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_LocationContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LocationContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_LocationContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_LocationContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_LocationContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_LocationContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_LocationContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_LocationContact_ScopedLookup");

                    b.HasIndex(new[] { "FkLocationId" }, "IX_LocationContacts_FkLocationId");

                    b.ToTable("LocationContacts", "hr");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PartyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPartyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PartyContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PartyContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PartyContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PartyContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PartyContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PartyContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PartyContact_ScopedLookup");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId" }, "IX_PersonContact_OwnerOrgUnit");

                    b.HasIndex(new[] { "OwnerPersonId" }, "IX_PersonContact_OwnerPerson");

                    b.HasIndex(new[] { "OwnerOrganizationUnitId", "OwnerPersonId" }, "IX_PersonContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPartyId" }, "IX_PersonContacts_FkPartyId");

                    b.ToTable("PartyContacts", "people");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PhoneBookInfoView", b =>
                {
                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Email");

                    b.Property<string>("EmploymentContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Fax");

                    b.Property<string>("EmploymentContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Mobile");

                    b.Property<string>("EmploymentContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmploymentContact_Phone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLevelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationUnitsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Address");

                    b.Property<string>("PartyEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Email");

                    b.Property<string>("PartyMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Mobile");

                    b.Property<string>("PartyPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Party_Phone");

                    b.Property<string>("PostContactEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Email");

                    b.Property<string>("PostContactFax")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Fax");

                    b.Property<string>("PostContactMobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Mobile");

                    b.Property<string>("PostContactPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostContact_Phone");

                    b.ToTable((string)null);

                    b.ToView("PhoneBook_Info_View", "phonebook");
                });

            modelBuilder.Entity("Contact.Domain.Entities.PostContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ContactType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PostContact");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PostContact_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_PostContact_CreatedBy");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ModifiedAt")
                        .HasDatabaseName("IX_PostContact_ModifiedAt");

                    b.HasIndex("ModifiedBy")
                        .HasDatabaseName("IX_PostContact_ModifiedBy");

                    b.HasIndex("OwnerOrganizationUnitId")
                        .HasDatabaseName("IX_PostContact_OwnerOrgUnit");

                    b.HasIndex("OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_OwnerPerson");

                    b.HasIndex("OwnerOrganizationUnitId", "OwnerPersonId")
                        .HasDatabaseName("IX_PostContact_ScopedLookup");

                    b.HasIndex(new[] { "FkPostId" }, "IX_PersonContacts_FkPostId");

                    b.ToTable("PostContacts", "hr");
                });

            modelBuilder.Entity("Core.Domain.Common.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("TypeName");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentId");

                    b.HasIndex("PostId");

                    b.ToTable("Assignment", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CostCenter", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkEmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkEmploymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkNaturalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentStatusId");

                    b.HasIndex("EmploymentTypeId");

                    b.ToTable("Employment", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkEmploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentId");

                    b.HasIndex("LocationId");

                    b.ToTable("EmploymentLocations", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentStatus", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentType", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grade", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobLevel", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobTitle", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Location", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("OrganizationUnit", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkCostCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkJobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPermissionAssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("GradeId");

                    b.HasIndex("JobLevelId");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("OrganizationUnitId");

                    b.HasIndex("ParentId");

                    b.ToTable("Post", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.PostLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PostId");

                    b.ToTable("PostLocations", "contact");
                });

            modelBuilder.Entity("HR.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("Assignments")
                        .HasForeignKey("EmploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.Post", "Post")
                        .WithMany("Assignments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.HasOne("HR.Domain.Entities.EmploymentStatus", "EmploymentStatus")
                        .WithMany("Employments")
                        .HasForeignKey("EmploymentStatusId");

                    b.HasOne("HR.Domain.Entities.EmploymentType", "EmploymentType")
                        .WithMany("Employments")
                        .HasForeignKey("EmploymentTypeId");

                    b.Navigation("EmploymentStatus");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentLocation", b =>
                {
                    b.HasOne("HR.Domain.Entities.Employment", "Employment")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("EmploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.Location", "Location")
                        .WithMany("EmploymentLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employment");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.HasOne("HR.Domain.Entities.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.HasOne("HR.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("Posts")
                        .HasForeignKey("CostCenterId");

                    b.HasOne("HR.Domain.Entities.Grade", "Grade")
                        .WithMany("Posts")
                        .HasForeignKey("GradeId");

                    b.HasOne("HR.Domain.Entities.JobLevel", "JobLevel")
                        .WithMany("Posts")
                        .HasForeignKey("JobLevelId");

                    b.HasOne("HR.Domain.Entities.JobTitle", "JobTitle")
                        .WithMany("Posts")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.OrganizationUnit", "OrganizationUnit")
                        .WithMany("Posts")
                        .HasForeignKey("OrganizationUnitId");

                    b.HasOne("HR.Domain.Entities.Post", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CostCenter");

                    b.Navigation("Grade");

                    b.Navigation("JobLevel");

                    b.Navigation("JobTitle");

                    b.Navigation("OrganizationUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HR.Domain.Entities.PostLocation", b =>
                {
                    b.HasOne("HR.Domain.Entities.Location", "Location")
                        .WithMany("PostLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Entities.Post", "Post")
                        .WithMany("PostLocations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HR.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Employment", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("EmploymentLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentStatus", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.EmploymentType", b =>
                {
                    b.Navigation("Employments");
                });

            modelBuilder.Entity("HR.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobLevel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.JobTitle", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EmploymentLocations");

                    b.Navigation("PostLocations");
                });

            modelBuilder.Entity("HR.Domain.Entities.OrganizationUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("HR.Domain.Entities.Post", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");

                    b.Navigation("PostLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
