// <auto-generated />
using System;
using HR.IrisaSync.Extention.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.IrisaSync.Extention.Migrations
{
    [DbContext(typeof(IrisaExtentionDbContext))]
    [Migration("20260802044307_Edit_2_IrisaSync")]
    partial class Edit_2_IrisaSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.IrisaSync.Extention.Entities.IrisaSyncJobLevelMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrisaJobLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IrisaJobLevelId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_IrisaSyncJobLevelMap");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "FkJobLevelId" }, "IX_Assignments_JobLevelId");

                    b.HasIndex(new[] { "FkJobLevelId" }, "IX_FkJobLevelId_Unique")
                        .IsUnique()
                        .HasFilter("[FkJobLevelId] IS NOT NULL");

                    b.HasIndex(new[] { "IrisaJobLevelId" }, "IX_IrisaJobLevelId_Unique")
                        .IsUnique()
                        .HasFilter("[IrisaJobLevelId] IS NOT NULL");

                    b.ToTable("IrisaSyncJobLevelMap", "hr");
                });

            modelBuilder.Entity("HR.IrisaSync.Extention.Entities.IrisaSyncJobTitleMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkJobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrisaJobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IrisaJobTitleId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IrisaJobTitleUseCount")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_IrisaSyncJobTitleMap");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "FkJobTitleId" }, "IX_Assignments_JobTitleId");

                    b.HasIndex(new[] { "FkJobTitleId" }, "IX_FkJobTitleId_Unique")
                        .IsUnique()
                        .HasFilter("[FkJobTitleId] IS NOT NULL");

                    b.HasIndex(new[] { "IrisaJobTitleId" }, "IX_IrisaJobTitleId_Unique")
                        .IsUnique()
                        .HasFilter("[IrisaJobTitleId] IS NOT NULL");

                    b.ToTable("IrisaSyncJobTitleMap", "hr");
                });

            modelBuilder.Entity("HR.IrisaSync.Extention.Entities.IrisaSyncOrganizationUnitMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkOrganizationUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrisaOrganizationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IrisaOrganizationUnitId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrganizationUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_IrisaSyncOrganizationUnitMap");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex(new[] { "FkOrganizationUnitId" }, "IX_Assignments_OrganizationUnitId");

                    b.HasIndex(new[] { "FkOrganizationUnitId" }, "IX_FkOrganizationUnitId_Unique")
                        .IsUnique()
                        .HasFilter("[FkOrganizationUnitId] IS NOT NULL");

                    b.HasIndex(new[] { "IrisaOrganizationUnitId" }, "IX_IrisaOrganizationUnitId_Unique")
                        .IsUnique()
                        .HasFilter("[IrisaOrganizationUnitId] IS NOT NULL");

                    b.ToTable("IrisaSyncOrganizationUnitMap", "hr");
                });
#pragma warning restore 612, 618
        }
    }
}
